#! /bin/sh
# $OpenLDAP$
## This work is part of OpenLDAP Software <http://www.openldap.org/>.
##
## Copyright 1998-2017 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh
unset LDAPNOINIT

mkdir -p $TESTDIR $DBDIR1
cp -r $DATADIR/ssl $TESTDIR

cd $TESTDIR/ssl && ./create-crt.sh -s
cd $TESTWD


echo "Starting slapd on TCP/IP port $PORT1..."
. $CONFFILTER $BACKEND $MONITORDB < $TLSCONF > $CONF1
$SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"

sleep 1

echo "TLS_CACERT $TESTDIR/ssl/ca/certs/testsuiteCA.crt" > $TESTDIR/ldapconf

echo "Using ldapsearch with startTLS"
for i in 0 1 2 3 4 5; do
	LDAPCONF=$TESTDIR/ldapconf $LDAPSEARCH -ZZ -b "" -s base -h $LOCALHOST -p $PORT1 \
		'@extensibleObject' > $SEARCHOUT 2>&1
	RC=$?
	if test $RC = 0 ; then
		break
	fi
	echo "Waiting 5 seconds for slapd to start..."
	sleep 5
done

if test $RC = 0 ; then
	echo "Using ldapsearch with ldaps"
#	LDAPCONF=$TESTDIR/ldapconf $LDAPSEARCH -b "cn=Subschema" -s base -h $LOCALHOST -p $PORT1 \
#		'(&(objectClasses=top)(objectClasses=2.5.6.0))' cn objectClass \
#		>> $SEARCHOUT  2>&1
#	RC=$?
fi

test $KILLSERVERS != no && kill -HUP $KILLPIDS

cat $SEARCHOUT

if test $RC != 0 ; then
	echo ">>>>> Test failed"
else
	echo ">>>>> Test succeeded"
	RC=0
fi

test $KILLSERVERS != no && wait

exit $RC
